name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true

      - name: Download Pico-8 assets
        env:
          PICO8_HOST: ${{ secrets.pico8_host }}
          PICO8_HOST_USER: ${{ secrets.pico8_host_user }}
          PICO8_HOST_PASSWORD: ${{ secrets.pico8_host_password }}
        run: |
          curl \
            --fail \
            --silent \
            --show-error \
            --user "${PICO8_HOST_USER}:${PICO8_HOST_PASSWORD}" \
            "${PICO8_HOST}" \
            --output ./pico8.zip

      - name: Extract Pico-8
        run: unzip -o pico8.zip

      - name: Add Pico-8 to PATH
        run: echo "${{ github.workspace }}/pico-8" >> "$GITHUB_PATH"
    
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Build
        working-directory: ${{ github.workspace }}
        run: xvfb-run -a python build.py

      - name: Upload release assets
        uses: actions/forgejo-release@v2.13.4
        with:
          direction: upload
          url: ${{ github.server_url }}
          repo: ${{ github.repository }}
          token: ${{ secrets.FORGEJO_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          release-dir: build
          override: true

      - name: Upload to itch.io (web)
        uses: https://github.com/robpc/itchio-upload-action@v1
        with:
          path: build/picogreed_web.zip
          project: anthracitesoftware/picogreed
          channel: web
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCH_TOKEN }}

      - name: Upload to itch.io (windows)
        uses: https://github.com/robpc/itchio-upload-action@v1
        with:
          path: build/picogreed_windows.zip
          project: anthracitesoftware/picogreed
          channel: windows
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCH_TOKEN }}

      - name: Upload to itch.io (linux)
        uses: https://github.com/robpc/itchio-upload-action@v1
        with:
          path: build/picogreed_linux.zip
          project: anthracitesoftware/picogreed
          channel: linux
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCH_TOKEN }}

      - name: Upload to itch.io (mac)
        uses: https://github.com/robpc/itchio-upload-action@v1
        with:
          path: build/picogreed_osx.zip
          project: anthracitesoftware/picogreed
          channel: mac
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCH_TOKEN }}

      - name: Upload to itch.io (p8)
        uses: https://github.com/robpc/itchio-upload-action@v1
        with:
          path: build/picogreed.p8.png
          project: anthracitesoftware/picogreed
          channel: pico8
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCH_TOKEN }}
